const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.custom,
		C3.Behaviors.Flash,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Rotate,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.custom.Acts.SetSpeed,
		C3.Behaviors.custom.Cnds.CompareSpeed,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.custom.Acts.SetEnabled,
		C3.Behaviors.Flash.Acts.Flash,
		C3.ScriptsInEvents.Efase1_Event22_Act4,
		C3.ScriptsInEvents.Efase1_Event24_Act3,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{Mosaico: 0},
	{TelaFundo: 0},
	{Pedra: 0},
	{Arvore: 0},
	{Arvore2: 0},
	{Barril: 0},
	{Arbusto: 0},
	{Arbusto2: 0},
	{Pedrinha: 0},
	{Bau: 0},
	{Porta: 0},
	{Sólido: 0},
	{sensor_solido: 0},
	{Moeda: 0},
	{CentrarEm: 0},
	{Plataforma: 0},
	{Rei: 0},
	{SPEED: 0},
	{DIRECAO: 0},
	{HORIZONTAL: 0},
	{Personalizado: 0},
	{Piscar: 0},
	{Dragao: 0},
	{Trap_fogo: 0},
	{Vidasanimacao: 0},
	{Itens_Hud: 0},
	{Sensor_Dragao: 0},
	{Mouse: 0},
	{Teclado: 0},
	{Áudio: 0},
	{Caixa: 0},
	{Mosaico2: 0},
	{Masmorra: 0},
	{Senóide: 0},
	{Suporte: 0},
	{JoiaReal: 0},
	{TxtMoedas: 0},
	{Txt_Moedas2: 0},
	{Sprite: 0},
	{Btn_Start: 0},
	{Btn_History: 0},
	{Txt_Criacao: 0},
	{Tela_GameOver: 0},
	{GameOver: 0},
	{Btn_Voltarjogo: 0},
	{Btn_Menu: 0},
	{Tela_History: 0},
	{Txt_History: 0},
	{Btn_Voltar: 0},
	{Girar: 0},
	{Chave: 0},
	{Chave_HUD: 0},
	{Tela: 0},
	{Txt_Itens: 0},
	{Texto: 0},
	{Tela_Menu: 0},
	{Btn_Info: 0},
	{Setas: 0},
	{Texto2: 0},
	{Teclas_Espaco: 0},
	{Tecla_Espaco: 0},
	{Tela_Info: 0},
	{Vidasanimacao2: 0},
	{Vidas: 0},
	{Moedas: 0}
];

self.InstanceType = {
	Mosaico: class extends self.ITilemapInstance {},
	TelaFundo: class extends self.ITiledBackgroundInstance {},
	Pedra: class extends self.ISpriteInstance {},
	Arvore: class extends self.ISpriteInstance {},
	Arvore2: class extends self.ISpriteInstance {},
	Barril: class extends self.ISpriteInstance {},
	Arbusto: class extends self.ISpriteInstance {},
	Arbusto2: class extends self.ISpriteInstance {},
	Pedrinha: class extends self.ISpriteInstance {},
	Bau: class extends self.ISpriteInstance {},
	Porta: class extends self.ISpriteInstance {},
	sensor_solido: class extends self.ISpriteInstance {},
	Rei: class extends self.ISpriteInstance {},
	Moeda: class extends self.ISpriteInstance {},
	Dragao: class extends self.ISpriteInstance {},
	Trap_fogo: class extends self.ISpriteInstance {},
	Vidasanimacao: class extends self.ISpriteInstance {},
	Itens_Hud: class extends self.ISpriteInstance {},
	Sensor_Dragao: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Teclado: class extends self.IInstance {},
	Áudio: class extends self.IInstance {},
	Caixa: class extends self.ISpriteInstance {},
	Mosaico2: class extends self.ITilemapInstance {},
	Masmorra: class extends self.ITiledBackgroundInstance {},
	Suporte: class extends self.ISpriteInstance {},
	JoiaReal: class extends self.ISpriteInstance {},
	TxtMoedas: class extends self.ITextInstance {},
	Plataforma: class extends self.ISpriteInstance {},
	Txt_Moedas2: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Btn_Start: class extends self.ISpriteInstance {},
	Btn_History: class extends self.ISpriteInstance {},
	Txt_Criacao: class extends self.ITextInstance {},
	Tela_GameOver: class extends self.ITiledBackgroundInstance {},
	GameOver: class extends self.ISpriteInstance {},
	Btn_Voltarjogo: class extends self.ISpriteInstance {},
	Btn_Menu: class extends self.ISpriteInstance {},
	Tela_History: class extends self.ITiledBackgroundInstance {},
	Txt_History: class extends self.ITextInstance {},
	Btn_Voltar: class extends self.ISpriteInstance {},
	Chave: class extends self.ISpriteInstance {},
	Chave_HUD: class extends self.ISpriteInstance {},
	Tela: class extends self.ITiledBackgroundInstance {},
	Txt_Itens: class extends self.ITextInstance {},
	Texto: class extends self.ITextInstance {},
	Tela_Menu: class extends self.ITiledBackgroundInstance {},
	Btn_Info: class extends self.ISpriteInstance {},
	Setas: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Teclas_Espaco: class extends self.ISpriteInstance {},
	Tecla_Espaco: class extends self.ITextInstance {},
	Tela_Info: class extends self.ITiledBackgroundInstance {},
	Vidasanimacao2: class extends self.ISpriteInstance {}
}